version: "3"
services:
  thehive:
    image: strangebee/thehive:5.3
    depends_on:
      - cassandra
      - elasticsearch
      - minio
    ports:
      - "9000:9000"
    environment:
      - JVM_OPTS="-Xms2048M -Xmx2048M"
    command:
      - --secret
      - "mySecretForTheHive"
      - "--cql-hostnames" 
      - "cassandra" 
      - "--index-backend" 
      - "elasticsearch" 
      - "--es-hostnames" 
      - "elasticsearch" 
      - "--s3-endpoint"
      - "http://minio:9000"
      - "--s3-access-key"
      - "minioadmin"
      - "--s3-secret-key"
      - "minioadmin"
      - "--s3-bucket"
      - "thehive"
      - "--s3-use-path-access-style"
    networks:
      - soc_network

  cassandra:
    image: 'cassandra:4'
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=1024M
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - soc_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    ports:
      - "9201:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - soc_network

  minio:
    image: quay.io/minio/minio
    command: ["minio", "server", "/data", "--console-address", ":9090"]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9090:9090"
    volumes:
      - "miniodata:/data"
    networks:
      - soc_network

volumes:
  miniodata:
  cassandradata:
  elasticsearchdata:

networks:
  soc_network:
    external: true